const {parseBody,turso,rowsFrom,verify,getCookie}=require('../../lib/auth');
const s=v=>v==null?'':String(v).trim(); const ci=v=>s(v).replace(/\D/g,'').slice(0,20);
const edad=f=>{if(!f)return 0;const d=new Date(s(f)+'T00:00:00');if(Number.isNaN(d.getTime()))return 0;const n=new Date();let e=n.getFullYear()-d.getFullYear();const m=n.getMonth()-d.getMonth();if(m<0||(m===0&&n.getDate()<d.getDate()))e--;return e>=0&&e<=130?e:0};
async function actor(req){const se=verify(getCookie(req,'erp_session'));if(!se)return null;return rowsFrom(await turso([{q:'SELECT id,usuario,rol FROM usuarios WHERE id=? AND activo=1 LIMIT 1',params:[se.uid]}]))[0]||null}
module.exports=async(req,res)=>{if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const a=await actor(req);if(!a||!['J','A','O'].includes(a.rol))return res.status(401).json({error:'Sesión no válida'});const b=parseBody(req),action=s(b.action);try{
if(['importar','reparar_edades','reset_cne'].includes(action)&&!['J','A'].includes(a.rol))return res.status(403).json({error:'Se requiere Jefe o Administrador para esta operación administrativa'});
if(action==='importar'){const rows=Array.isArray(b.rows)?b.rows:[];if(!rows.length)return res.status(400).json({error:'No hay registros'});const centers=Array.isArray(b.centros)?b.centros:[];let c=0,p=0;const statements=[];for(const x of centers){if(!s(x.codigo))continue;statements.push({q:'INSERT OR IGNORE INTO centros(codigo,nombre,municipio,parroquia,estado,mesas,cod_estado,cod_municipio,cod_parroquia) VALUES(?,?,?,?,?,?,1,?,?)',params:[s(x.codigo),s(x.nombre),s(x.municipio),s(x.parroquia),s(x.estado),1,s(x.cod_municipio),s(x.cod_parroquia)]});c++}for(const x of rows){const ced=ci(x.ced);if(!/^\d{5,9}$/.test(ced))continue;statements.push({q:'INSERT OR IGNORE INTO padron(cedula,letra,p_apellido,s_apellido,p_nombre,s_nombre,sexo,fecha_nac,edad,codigo_estado,estado,codigo_municipio,municipio,codigo_parroquia,parroquia,centro_votacion,nombre_cv) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',params:[ced,s(x.letra)||'V',s(x.pa),s(x.sa),s(x.pn),s(x.sn),s(x.sexo),s(x.fn),edad(x.fn),s(x.codEst),s(x.estado),s(x.codMun),s(x.mun),s(x.codPar),s(x.par),s(x.cvCod),s(x.cvNom)]});p++}for(let i=0;i<statements.length;i+=300)await turso(statements.slice(i,i+300));await turso([{q:'INSERT INTO actividad(tipo,texto,usuario_id) VALUES(?,?,?)',params:['sys','Importación de padrón: '+p+' registros • '+s(b.fname),a.id]}]);return res.json({ok:true,centros:c,electores:p})}
if(action==='reparar_edades'){const rows=rowsFrom(await turso([{q:'SELECT cedula,fecha_nac FROM padron'}]));for(let i=0;i<rows.length;i+=300)await turso(rows.slice(i,i+300).map(x=>({q:'UPDATE padron SET edad=? WHERE cedula=?',params:[edad(x.fecha_nac),x.cedula]})));await turso([{q:'INSERT INTO actividad(tipo,texto,usuario_id) VALUES(?,?,?)',params:['sys','Edades del padrón recalculadas: '+rows.length,a.id]}]);return res.json({ok:true,fixed:rows.length})}
if(action==='reset_cne'){await turso([{q:'DELETE FROM verificaciones_votacion'},{q:'DELETE FROM mesa_miembros'},{q:'DELETE FROM mesa_operativa'},{q:'DELETE FROM actas_mesa'},{q:'DELETE FROM padron'},{q:'INSERT INTO actividad(tipo,texto,usuario_id) VALUES(?,?,?)',params:['sys','Padrón CNE reiniciado y control electoral limpiado',a.id]}]);return res.json({ok:true})}
return res.status(400).json({error:'Acción no permitida'})}catch(e){console.error(e);return res.status(500).json({error:e.message||'Error'})}};